version: '3.8'

services:
  backend:
    container_name: medcontrol_api
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - medcontrol-network
    restart: unless-stopped

  postgres:
    container_name: medcontrol_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medcontrol
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - medcontrol-network
    restart: unless-stopped

networks:
  medcontrol-network:
    driver: bridge

volumes:
  postgres-data:
